input {
  file {
    path => "/logs/**/*.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb-app-logs"
    codec => json {
      target => "json"
    }
  }

  tcp {
    port => 5000
    codec => json_lines
  }

  udp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [json] {
    mutate {
      add_field => {
        "app_log_message" => "%{[json][message]}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "b3-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}