global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "gestor-ativos-brutos"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "gestor-ativos-brutos:8091"

  - job_name: "gerar-insights"
    static_configs:
      - targets:
          - "gerar-insights:8080"
